name: Update Download Counts

on:
  schedule:
    - cron: '0 0 * * *'

yamljobs:
  update-counts:
    runs-on: ubuntu-l
    steps:
    - name: Checkout
      uses: actions/checkout@v

    - name: Fetch download
      id: fetch
      run: |
        DOWNLOAD_COUNT=$(curl -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
        https://api.github.com/repos/sskyNS/RoastDuck-CFWPack/releases | \
        jq '[.[] | .assets[] | select(.name == "RDPv8.6.0.zip").download_count] | add')
        echo ::set-output name=count::$DOWNLOAD
    - name: Update README.md
      run: |
        sed -i "s/<!--download_count-->/Downloads: ${{ steps.fetch_counts.outputs.count }}/g" README.md
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "Update download counts"
        git push
  
