name: Update Download Counts

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-counts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch download counts
      id: fetch_counts
      run: |
        DOWNLOAD_COUNT=$(curl -H "Authorization: token ${{ secrets.github_pat_11A44YFOY0KylidkdeYCuC_tF5hhmoCL3i2LXPO73kGMeEpzsDSVOdKtMTvyxxYjfOBTPPYJUn5GaTC7r }}" \
        https://api.github.com/repos/sskyNS/RoastDuck-CFWPack/releases | \
        jq '[.[] | .assets[] | select(.name == "RDPv8.6.0.zip").download_count] | add')
        echo ::set-output name=count::$DOWNLOAD_COUNT
      
    - name: Update README.md
      run: |
        sed -i "s/<!--download_count-->/Downloads: ${{ steps.fetch_counts.outputs.count }}/g" README.md
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "Update download counts"
        git push
  
